"use client";

import { SessionProvider } from "next-auth/react";
import localFont from "next/font/local";
import "./globals.css";
import { RegistrationProvider } from "@/context/RegistrationContext"; // RegistrationProviderをインポート

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-snack`}
      >
        <RegistrationProvider>
          {" "}
          {/* アプリ全体をRegistrationProviderでラップ */}
          <SessionProvider>{children}</SessionProvider>
        </RegistrationProvider>
      </body>
    </html>
  );
}
